name: gosquash
version: "3.8"

services:
  database:
    container_name: gosquash-database
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      # Persist the database data
      - ./volumes/db/data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - gosquash-network

  api:
    container_name: gosquash-api
    build:
      context: ../
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: ${API_PORT}
      # DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    networks:
      - gosquash-network

networks:
  gosquash-network:
    driver: bridge
